name: authenticator_app
description: Second factor keycloak authenticator app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2024.07.0+6

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^16.1.0
  get_it: ^8.2.0
  flutter_svg: ^2.0.7
  keycloak_authenticator:
    path: ./packages/keycloak_authenticator
  mobile_scanner: ^7.0.1
  date_format: ^2.0.7
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GrueneType
      fonts:
        - asset: assets/fonts/GrueneType/GrueneType-BlackCondensedItalic.otf
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans/PTS55F.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/PTSans/PTS56F.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PTSans/PTS75F.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/PTSans/PTS76F.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"