description: >
  Installs and caches the Android SDK build-tools 30.0.3
  so that subsequent builds do not need to install during flutter builds.
  This saves time to build and CircleCI credits.
  https://github.com/flutter/flutter/issues/83573
  https://github.com/flutter/flutter/issues/41462
parameters:
  cache-version:
    default: v1
    description: >-
      Change the default cache version if you need to clear the cache for any
      reason.
    type: string
steps:
  - restore_cache:
      keys:
        - android-sdk-build-tools-<<parameters.cache-version>>-{{ arch }}
  - run:
      command: sdkmanager "build-tools;30.0.3"
      name: Install Android SDK Build-Tools 30.0.3
  - save_cache:
      key: >-
        android-sdk-build-tools-<<parameters.cache-version>>-{{ arch }}
      paths:
        - ~/android-sdk/build-tools/30.0.3
