description: Restores and saves fastlane cache of the passed directory.
parameters:
  directory:
    type: string
steps:
  - restore_cache:
      name: Restore Ruby Cache
      keys:
        - v1-gems-{{ arch }}-{{ checksum "<< parameters.directory >>/Gemfile.lock" }}
        - v1-gems-{{ arch }}
  - run:
      name: Install fastlane
      command: |
        bundle config set path '~/.bundle'
        bundle config set frozen true
        bundle check || bundle install
      working_directory: << parameters.directory >>
  - save_cache:
      name: Save Ruby Cache
      key: v1-gems-{{ arch }}-{{ checksum "<< parameters.directory >>/Gemfile.lock" }}
      paths:
        - << parameters.directory >>/vendor/bundle
