when:
    equal: [<< pipeline.parameters.workflow_type >>, beta_delivery]
jobs:
  - bump_version:
      prepare_delivery: true
      context:
        - github

  - build_android:
      context:
        - app_signing_android
      requires:
        - bump_version
  - deliver_android:
      production_delivery: false
      context:
        - verdigado_google_playstore
      requires:
        - build_android

  - build_ios:
      context:
        - verdigado_app_signing_ios
      requires:
        - bump_version
  - deliver_ios:
      production_delivery: false
      context:
        - verdigado_apple_appstore
      requires:
        - build_ios

  - notify_release:
      production_delivery: false
      context:
        - github
      requires:
        - deliver_android
        - deliver_ios
