when:
  equal: [ develop, << pipeline.git.branch >> ]
jobs:
  - bump_version
  - build_android:
      name: build_appbundle
      build_target: appbundle
      build_path: bundle/release/app-release.aab
      requires:
        - bump_version
  - build_android:
      name: build_apk
      build_target: apk
      build_path: apk/release/app-release.apk
      requires:
        - bump_version
  - beta_deploy_android:
      requires:
        - build_appbundle
  - create_release:
      additional_args: --prerelease
      version_suffix: -beta
      requires:
        - build_apk
