when:
  equal: [ develop, << pipeline.git.branch >> ]
jobs:
  - bump_version
  - build_android:
      requires:
        - bump_version
  - test_deploy_android:
      requires:
        - build_android
