commands:
    restore_bash_env:
        steps:
            - attach_workspace:
                at: .
            - run: cat bash.env >> $BASH_ENV
jobs:
    build_android:
        docker:
            - image: melegiul/kc-auth-app-android:2024.01.1
        parameters:
            build_name:
                type: string
            build_path:
                type: string
            build_target:
                type: string
        steps:
            - checkout
            - flutter/install_sdk_and_pub:
                version: 3.16.9
            - flutter/install_android_gem
            - android/decode-keystore:
                keystore-location: android/app/upload-keystore.jks
            - android/create-keystore-properties:
                release-keystore: ./upload-keystore.jks
                working-directory: android
            - restore_bash_env
            - run:
                command: flutter build << parameters.build_target >> --build-number ${BUILD_NUMBER} --build-name ${BUILD_NAME}
                name: Build appbundle
            - run:
                command: |
                    mkdir -p /tmp/android-builds
                    mv << parameters.build_path >> /tmp/android-builds/<< parameters.build_name >>
                name: Move android builds into workspace
            - persist_to_workspace:
                paths:
                    - << parameters.build_name >>
                root: /tmp/android-builds
    bump_version:
        docker:
            - image: cimg/base:2024.01
        steps:
            - checkout
            - run:
                command: |
                    ./bump_version.sh
                    cp $BASH_ENV bash.env
                name: Update pubspec.yaml version
            - persist_to_workspace:
                paths:
                    - bash.env
                root: .
            - run:
                command: |
                    git config user.email "technik@verdigado.com"
                    git config user.name "CircleCI"
                    git add pubspec.yaml
                    git commit -m "Bump version ${NEW_PUBSPEC_VERSION}" -m "[skip ci]"
                    git push origin "${CIRCLE_BRANCH}"
                name: Commit and push version bump
    create_release:
        docker:
            - image: cimg/base:2024.01
        parameters:
            additional_args:
                default: ""
                type: string
            version_suffix:
                default: ""
                type: string
        steps:
            - checkout
            - github-cli/setup
            - attach_workspace:
                at: /tmp/android-builds
            - restore_bash_env
            - run:
                command: |
                    TAG="v${BUILD_NAME}<< parameters.version_suffix >>"
                    gh release create "${TAG}" /tmp/android-builds/*.apk --target ${CIRCLE_BRANCH} --generate-notes << parameters.additional_args >>
                name: Create github release
    test_deploy_android:
        executor:
            name: android/android-docker
            tag: 2024.01.1
        steps:
            - checkout
            - attach_workspace:
                at: /tmp/android-builds
            - run: echo "Upload to test track"
            - run: ls -R /tmp/android-builds
orbs:
    android: circleci/android@2.4.0
    flutter: circleci/flutter@2.0.2
    github-cli: circleci/github-cli@2.3.0
version: 2.1
workflows:
    test_deploy:
        jobs:
            - bump_version
            - build_android:
                build_name: kc-auth-app.aab
                build_path: build/app/outputs/bundle/release/app-release.aab
                build_target: appbundle
                name: build_appbundle
                requires:
                    - bump_version
            - build_android:
                build_name: kc-auth-app.apk
                build_path: build/app/outputs/apk/release/app-release.apk
                build_target: apk
                name: build_apk
                requires:
                    - bump_version
            - test_deploy_android:
                requires:
                    - build_appbundle
            - create_release:
                additional_args: --prerelease
                requires:
                    - build_apk
                version_suffix: -beta
        when:
            equal:
                - develop
                - << pipeline.git.branch >>

