docker:
  - image: cimg/ruby:3.3.0
steps:
  - checkout
  - attach_workspace:
      at: .
  - android/create-google-play-key:
      working-directory: android
  - flutter/install_android_gem
  - run:
      name: Upload to play store
      command: |
        pwd
        ls -la ~
        BUNDLE_PATH=$(find ${CIRCLE_WORKING_DIRECTORY} -name app-release.aab)
        cd android
        bundle exec fastlane play_store_beta aab_path:${BUNDLE_PATH}
