docker:
  - image: cimg/android:2025.10.1-node
steps:
  - prepare_workspace
  - install_flutter:
      precache: android
  - install_fastlane:
      directory: android
  - run:
      name: '[FL] Prepare Android Keystore'
      command: bundle exec fastlane android keystore
      working_directory: android
  - run:
      name: '[FL] Build'
      command: bundle exec fastlane android build version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE}
      working_directory: android
  - run:
      name: Move artifacts
      command: |
        mv build/app/outputs/bundle/release/app-release.aab ~/attached_workspace/app-release.aab
        mv build/app/outputs/apk/release/app-release.apk ~/attached_workspace/app-release.apk
  - persist_to_workspace:
      root: ~/attached_workspace
      paths:
        - app-release.aab
        - app-release.apk
  - store_artifacts:
      path: ~/attached_workspace
