parameters:
  build_target:
    type: string
  build_path:
    type: string
  build_name:
    type: string
docker:
  - image: melegiul/kc-auth-app-android:2024.01.1
steps:
  - checkout
  - flutter/install_sdk_and_pub:
      version: 3.16.9
  - flutter/install_android_gem
  - android/decode-keystore:
      keystore-location: android/app/upload-keystore.jks
  - android/create-keystore-properties:
      working-directory: android
      release-keystore: ./upload-keystore.jks
  - restore_bash_env
  - run:
      name: Build appbundle
      command: flutter build << parameters.build_target >> --build-number ${BUILD_NUMBER} --build-name ${BUILD_NAME}
  - run:
      name: Move android builds into workspace
      command: |
        mkdir -p /tmp/android-builds
        mv << parameters.build_path >> /tmp/android-builds/<< parameters.build_name >>
  - persist_to_workspace:
      root: /tmp/android-builds
      paths:
        - << parameters.build_name >>
