parameters:
  prepare_delivery:
    description: Whether to prepare for a delivery. If true, the version bump is committed.
    type: boolean
    default: false
docker:
  - image: cimg/node:20.18.0
resource_class: small
steps:
  - prepare_workspace
  - install_app_toolbelt
  - run:
      name: Calculate next version name
      command: echo "export NEW_VERSION_NAME=$(yarn --silent app-toolbelt v0 version calc | jq .versionName)" >> ${BASH_ENV}
      working_directory: tools
  - run:
      name: Calculate next version code
      command: echo "export NEW_VERSION_CODE=$(yarn --silent app-toolbelt v0 version calc | jq .versionCode)" >> ${BASH_ENV}
      working_directory: tools
  - when:
      condition: << parameters.prepare_delivery >>
      steps:
        - run:
            name: Bump git version
            command: yarn app-toolbelt v0 release bump-to ${NEW_VERSION_NAME} ${NEW_VERSION_CODE} --private-key ${GITHUB_PRIVATE_KEY} --github-app 1059509 --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --branch ${CIRCLE_BRANCH} --platforms all
            working_directory: tools
  - persist_environment_variables
