parameters:
  production_delivery:
    description: Whether to deliver the build to production.
    type: boolean
macos:
  xcode: 16.3.0
steps:
  - prepare_workspace
  - install_fastlane:
      directory: ios
  - when:
      condition: << parameters.production_delivery >>
      steps:
        - run:
            name: '[FL] Apple AppStore Upload'
            command: bundle exec fastlane ios production_upload ipa_path:attached_workspace/app-release.ipa version_name:${NEW_VERSION_NAME}
            working_directory: ios
  - unless:
      condition: << parameters.production_delivery >>
      steps:
        - run:
            name: '[FL] Apple TestFlight Upload'
            command: bundle exec fastlane ios beta_upload ipa_path:attached_workspace/app-release.ipa
            working_directory: ios
