parameters:
  production_delivery:
    description: Whether to deliver the build to production.
    type: boolean
docker:
  - image: cimg/node:22.20.0
resource_class: small
steps:
  - prepare_workspace
  - install_app_toolbelt
  - run:
      name: Create github release
      command: echo "export RELEASE_ID='$(yarn --silent app-toolbelt v0 release create all ${NEW_VERSION_NAME} ${NEW_VERSION_CODE} --private-key ${GITHUB_PRIVATE_KEY} --github-app 1059509 --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} <<# parameters.production_delivery >>--production-release<</ parameters.production_delivery >>)'" >> ${BASH_ENV}
      working_directory: tools
  - run:
      name: Upload android apk to github release
      command: yarn app-toolbelt v0 release upload --releaseId ${RELEASE_ID} --files "$(ls ~/attached_workspace/*.apk)" --private-key ${GITHUB_PRIVATE_KEY} --github-app 1059509 --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME}
      working_directory: tools
