macos:
  xcode: 16.3.0
steps:
  - prepare_workspace
  - install_fastlane:
      directory: ios
  - run:
      name: '[FL] Apple AppStore Promotion'
      command: bundle exec fastlane ios promote
      working_directory: ios
