docker:
  - image: cimg/android:2025.10.1-node
resource_class: small
steps:
  - prepare_workspace
  - install_fastlane:
      directory: android
  - run:
      name: '[FL] Google PlayStore Promotion'
      command: bundle exec fastlane android promote
      working_directory: android
