#!/bin/sh

#
# Install this using:
# ln -s ../../.github/hooks/pre-commit .git/hooks/pre-commit
#

# Regenerate circle-ci config-yml
CONFIG=$(git diff --cached --name-only .circleci/src)

echo "$CONFIG" | ./tools/circleci-update-config
echo "$CONFIG" | xargs git add .circleci/config.yml

DART_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.dart" | sed 's| |\\ |g')

if [ ! -z "$DART_FILES" ]; then
  if [ ! -x "$(command -v fvm)" ]; then
    echo "You need to install fvm in order to commit and format files"
    exit 1
  fi

  # Prettify all selected files
  # Run dart in the correct project folder to ensure correct dart project version
  echo "$DART_FILES" | xargs -I {} sh -c 'fvm dart format -l 120 . {}'

  # Add back the modified/prettified files to staging
  echo "$DART_FILES" | xargs git add
fi

exit 0
