# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build app bundle"
  lane :build_bundle do
    gradle(task: "bundle", build_type: "Release")
  end

  desc "Build app apk"
  lane :build_apk do
    gradle(task: "assemble", build_type: "Release")
  end

  desc "Delete the build directory"
  lane :clean do
    gradle(task: "clean")
  end
end
